In [1]:
# импортируем библиотеки pandas и numpy
import pandas as pd
import numpy as np
# импортируем функции kurtosis() и skew()
# для вычисления скоса и эксцесса
from scipy.stats import kurtosis
from scipy.stats import skew

In [2]:
# записываем CSV-файл в объект DataFrame
data = pd.read_csv('Data/StateFarm.csv', sep=';')
data.head(3)

Customer Lifetime Value  Income  Monthly Premium Auto  \
0             18975.456110   65999                   237   
1              4715.321344       0                    65   
2              5018.885233   54500                    63   

   Months Since Last Claim  Months Since Policy Inception  \
0                        1                             14   
1                       19                             56   
2                       28                             17   

   Number of Open Complaints  Number of Policies  Response  
0                          0                   6         0  
1                          0                   3         0  
2                          0                   6         0

In [3]:
# импортируем функцию train_test_split(), с помощью
# которой разбиваем данные на обучающие и тестовые
from sklearn.model_selection import train_test_split
# разбиваем данные на обучающие и тестовые: получаем обучающий
# массив признаков, тестовый массив признаков, обучающий массив
# меток, тестовый массив меток
X_train, X_test, y_train, y_test = train_test_split(data.drop('Response', axis=1), 
                                                    data['Response'], 
                                                    test_size=0.3,
                                                    stratify=data['Response'],
                                                    random_state=42)

In [4]:
X_train.iloc[0, 2] = 9999999
X_train.iloc[1, 2] = 9999999
X_train.iloc[2, 2] = 9999999
X_train.iloc[3, 2] = 9999999

In [5]:
X_train.head()

Customer Lifetime Value  Income  Monthly Premium Auto  \
6764             12200.785370   60282               9999999   
6435              5330.593183   84240               9999999   
4763             10426.085510   52342               9999999   
1543              3744.577726       0               9999999   
7863              2866.779811   81763                    72   

      Months Since Last Claim  Months Since Policy Inception  \
6764                       23                             87   
6435                       10                             51   
4763                       28                             28   
1543                        3                             32   
7863                       22                             12   

      Number of Open Complaints  Number of Policies  
6764                          0                   2  
6435                          0                   1  
4763                          3                   2  
1543                          0                   1  
7863                          1                   1

In [6]:
# импортируем класс StandardScaler, выполняющий стандартизацию
from sklearn.preprocessing import StandardScaler
# создаем модель стандартизации – экземпляр класса StandardScaler
standardscaler = StandardScaler()

In [7]:
# обучаем модель стандартизации, т.е. по каждому признаку 
# в обучающем массиве признаков вычисляем
# среднее значение признака и стандартное 
# отклонение признака для трансформации
standardscaler.fit(X_train)

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [8]:
# применяем модель стандартизации к обучающему массиву признаков: из исходного 
# значения признака вычитаем среднее значение признака, вычисленное 
# по ОБУЧАЮЩЕМУ массиву признаков, и результат делим на стандартное 
#отклонение признака, вычисленное по ОБУЧАЮЩЕМУ массиву признаков 
X_train_standardscaled = standardscaler.transform(X_train)

# применяем модель стандартизации к тестовому массиву признаков: из исходного 
# значения признака вычитаем среднее значение признака, вычисленное 
# по ОБУЧАЮЩЕМУ массиву признаков, и результат делим на стандартное 
# отклонение признака, вычисленное по ОБУЧАЮЩЕМУ массиву признаков 
X_test_standardscaled = standardscaler.transform(X_test)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """
/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  # This is added back by InteractiveShellApp.init_path()


In [9]:
print('min значение признака после масштабирования:\n {}'.format(
    X_train_standardscaled.min(axis=0)))
print('max значение признака после масштабирования:\n {}'.format(
    X_train_standardscaled.max(axis=0)))
print('mean значение признака после масштабирования:\n {}'.format(
    X_train_standardscaled.mean(axis=0)))
print('std значение признака после масштабирования:\n {}'.format(
    X_train_standardscaled.std(axis=0)))

min значение признака после масштабирования:
 [-0.87255522 -1.23461135 -0.02643121 -1.49705364 -1.73671359 -0.42181925
 -0.81640104]
max значение признака после масштабирования:
 [10.70896627  2.02740427 38.00986682  1.96699975  1.83506722  5.0673363
  2.56195116]
mean значение признака после масштабирования:
 [-2.94881993e-17 -8.47785730e-17 -2.45734994e-18 -9.15362853e-17
 -7.86351981e-17 -2.45734994e-18 -7.98638731e-18]
std значение признака после масштабирования:
 [1. 1. 1. 1. 1. 1. 1.]


In [10]:
print('скос признака до масштабирования:\n {}'.format(
    skew(X_train, axis=0)))
print('скос признака после масштабирования:\n {}'.format(
    skew(X_train_standardscaled, axis=0)))
print('эксцесс признака до масштабирования:\n {}'.format(
    kurtosis(X_train, axis=0)))
print('эксцесс признака после масштабирования:\n {}'.format(
    kurtosis(X_train_standardscaled, axis=0)))

скос признака до масштабирования:
 [ 3.19225751  0.28112472 37.98355721  0.27930269  0.04841951  2.75635549
  1.27032665]
скос признака после масштабирования:
 [ 3.19225751  0.28112472 37.98355721  0.27930269  0.04841951  2.75635549
  1.27032665]
эксцесс признака до масштабирования:
 [ 1.55711115e+01 -1.11676035e+00  1.44075064e+03 -1.07210527e+00
 -1.13514369e+00  7.54169688e+00  4.19060117e-01]
эксцесс признака после масштабирования:
 [ 1.55711115e+01 -1.11676035e+00  1.44075064e+03 -1.07210527e+00
 -1.13514369e+00  7.54169688e+00  4.19060117e-01]


In [11]:
# импортируем класс MinMaxScaler, выполняющий стандартизацию
from sklearn.preprocessing import MinMaxScaler
# создаем модель стандартизации – экземпляр класса StandardScaler
minmaxscaler = MinMaxScaler()

In [12]:
# обучаем модель стандартизации, т.е. по каждому признаку 
# в обучающем массиве признаков вычисляем
# минимальное значение и диапазон признака
minmaxscaler.fit(X_train)

# применяем модель стандартизации к обучающему массиву признаков: из исходного 
# значения признака вычитаем минимальное значение признака, вычисленное 
# по ОБУЧАЮЩЕМУ массиву признаков, и результат делим на диапазон 
# признака, вычисленный по ОБУЧАЮЩЕМУ массиву признаков 
X_train_minmaxscaled = minmaxscaler.transform(X_train)

# применяем модель стандартизации к тестовому массиву признаков: из исходного 
# значения признака вычитаем минимальное значение признака, вычисленное 
# по ОБУЧАЮЩЕМУ массиву признаков, и результат делим на диапазон 
# признака, вычисленный по ОБУЧАЮЩЕМУ массиву признаков 
X_test_minmaxscaled = minmaxscaler.transform(X_test)

/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:334: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [13]:
print('минимальное значение признака после масштабирования:\n {}'.format(
    X_train_minmaxscaled.min(axis=0)))
print('максимальное значение признака после масштабирования:\n {}'.format(
    X_train_minmaxscaled.max(axis=0)))
print('среднее значение признака после масштабирования:\n {}'.format(
    X_train_minmaxscaled.mean(axis=0)))
print('стандартное отклонение признака после масштабирования:\n {}'.format(
    X_train_minmaxscaled.std(axis=0)))

минимальное значение признака после масштабирования:
 [0. 0. 0. 0. 0. 0. 0.]
максимальное значение признака после масштабирования:
 [1. 1. 1. 1. 1. 1. 1.]
среднее значение признака после масштабирования:
 [0.07534029 0.37848113 0.00069489 0.43216818 0.48623185 0.07684593
 0.24165658]
стандартное отклонение признака после масштабирования:
 [0.08634444 0.30655892 0.02629068 0.28867915 0.27997239 0.18217738
 0.29600229]


In [14]:
# импортируем класс RobustScaler, выполняющий стандартизацию
from sklearn.preprocessing import RobustScaler
# создаем модель стандартизации – экземпляр класса RobustScaler
robustscaler = RobustScaler()

In [15]:
# обучаем модель стандартизации, т.е. по каждому признаку 
# в обучающем массиве признаков вычисляем
# минимальное значение и диапазон признака
robustscaler.fit(X_train)

# применяем модель стандартизации к обучающему массиву признаков: из исходного 
# значения признака вычитаем первый квартиль признака, вычисленный 
# по ОБУЧАЮЩЕМУ массиву признаков, и результат делим на межквартильный
# размах признака, вычисленный по ОБУЧАЮЩЕМУ массиву признаков 
X_train_robustscaled = robustscaler.transform(X_train)

# применяем модель стандартизации к тестовому массиву признаков: из исходного 
# значения признака вычитаем первый квартиль признака, вычисленный
# по ОБУЧАЮЩЕМУ массиву признаков, и результат делим на межквартильный 
# размах признака, вычисленный по ОБУЧАЮЩЕМУ массиву признаков 
X_test_robustscaled = robustscaler.transform(X_test)

In [16]:
print('min значение признака после масштабирования:\n {}'.format(
    X_train_robustscaled.min(axis=0)))
print('max значение признака после масштабирования:\n {}'.format(
    X_train_robustscaled.max(axis=0)))
print('mean значение признака после масштабирования:\n {}'.format(
    X_train_robustscaled.mean(axis=0)))
print('std значение признака после масштабирования:\n {}'.format(
    X_train_robustscaled.std(axis=0)))

min значение признака после масштабирования:
 [-0.77007865 -0.53878018 -0.53658537 -0.82352941 -1.04347826  0.
 -0.33333333]
max значение признака после масштабирования:
 [1.53303007e+01 1.05108410e+00 2.43900390e+05 1.23529412e+00
 1.10869565e+00 5.00000000e+00 2.33333333e+00]
mean значение признака после масштабирования:
 [4.42928651e-01 6.29534426e-02 1.68948811e+02 6.62286011e-02
 2.97724214e-03 3.84229639e-01 3.11084212e-01]
std значение признака после масштабирования:
 [1.39017826e+00 4.87387083e-01 6.41232032e+03 5.94339434e-01
 6.02549267e-01 9.10886921e-01 7.89339449e-01]
