In [1]:
# импортируем необходимые библиотеки
import pandas as pd
import numpy as np

# записываем CSV-файл в объект DataFrame
train = pd.read_csv('https://raw.githubusercontent.com/'
                    'DunderData/Machine-Learning-Tutorials/'
                    'master/data/housing/train.csv')

# выводим первые 5 наблюдений
train.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008        WD         Normal     208500  
1      5   2007        WD         Normal     181500  
2      9   2008        WD         Normal     223500  
3      2   2006        WD        Abnorml     140000  
4     12   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [2]:
# смотрим форму обучающего датафрейма
train.shape

(1460, 81)

In [3]:
# создаем массив меток
y = train.pop('SalePrice').values

In [4]:
# выводим частоты категорий переменной HouseStyle
vc = train['HouseStyle'].value_counts()
vc

1Story    726
2Story    445
1.5Fin    154
SLvl       65
SFoyer     37
1.5Unf     14
2.5Unf     11
2.5Fin      8
Name: HouseStyle, dtype: int64

In [5]:
# создаем объект DataFrame с одним столбцом
hs_train = train[['HouseStyle']].copy()
hs_train.ndim

2

In [6]:
# импортируем класс OneHotEncoder
from sklearn.preprocessing import OneHotEncoder
# создаем экземпляр класса OneHotEncoder,
# будем возвращать плотный массив
ohe = OneHotEncoder(sparse=False)
# выполняем дамми-кодирование переменной
# HouseStyle в обучающем наборе
hs_train_transformed = ohe.fit_transform(hs_train)
# смотрим результаты
hs_train_transformed

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [7]:
# убеждаемся, что каждое уникальное значение
# получило свой столбец (8 уникальных значений
# даст 8 столбцов)
hs_train_transformed.shape

(1460, 8)

In [8]:
# запишем имена столбцов в объект feature_names
feature_names = ohe.get_feature_names()
# смотрим имена столбцов
feature_names

array(['x0_1.5Fin', 'x0_1.5Unf', 'x0_1Story', 'x0_2.5Fin', 'x0_2.5Unf',
       'x0_2Story', 'x0_SFoyer', 'x0_SLvl'], dtype=object)

In [9]:
# выведем первую строку преообразованных данных
row0 = hs_train_transformed[0]
row0

array([0., 0., 0., 0., 0., 1., 0., 0.])

In [10]:
# выясним имя переменной, которое
# в первой строке закодировано 1
feature_names[row0 == 1]

array(['x0_2Story'], dtype=object)

In [11]:
# смотрим значение исходного столбца
# HouseStyle в строке 0
hs_train.values[0]

array(['2Story'], dtype=object)

In [12]:
# выполним обратное преобразование
ohe.inverse_transform([row0])

array([['2Story']], dtype=object)

In [13]:
# выполняем инвертирование всего 
# преобразованного массива
hs_inv = ohe.inverse_transform(hs_train_transformed)
hs_inv

array([['2Story'],
       ['1Story'],
       ['2Story'],
       ...,
       ['2Story'],
       ['1Story'],
       ['1Story']], dtype=object)

In [14]:
# проверяем, совпадают ли массивы
np.array_equal(hs_inv, hs_train.values)

True

In [15]:
# выполняем дамми-кодирование переменной HouseStyle
# в тестовом наборе
test = pd.read_csv('https://raw.githubusercontent.com/'
                   'DunderData/Machine-Learning-Tutorials/'
                   'master/data/housing/test.csv')
hs_test = test[['HouseStyle']].copy()
hs_test_transformed = ohe.transform(hs_test)
hs_test_transformed

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [16]:
# убеждаемся, что каждое уникальное значение
# получило свой столбец (8 уникальных значений
# даст 8 столбцов)
hs_test_transformed.shape

(1459, 8)

In [17]:
# копируем переменную HouseStyle
# в тестовом наборе
hs_test = test[['HouseStyle']].copy()
# заменяем значение в переменной HouseStyle
hs_test.iloc[0, 0] = '3Story'
# выводим первые три наблюдения
hs_test.head(3)

HouseStyle
0     3Story
1     1Story
2     2Story

In [18]:
# выполняем дамми-кодирование переменной 
# HouseStyle в тестовом наборе
ohe.transform(hs_test)

ValueError: Found unknown categories ['3Story'] in column 0 during transform

In [19]:
# создаем экземпляр класса OneHotEncoder, задав 
# для параметра handle_unknown значение ignore
ohe = OneHotEncoder(sparse=False, handle_unknown='ignore')
# обучаем модель
ohe.fit(hs_train)
# выполняем дамми-кодирование переменной 
# HouseStyle в тестовом наборе
hs_test_transformed = ohe.transform(hs_test)
hs_test_transformed

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [20]:
# проверим, состоит ли первая строка из одних нулей
hs_test_transformed[0]

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
# копируем переменную HouseStyle
# в тестовом наборе
hs_test = test[['HouseStyle']].copy()
# заменяем первые два значения
# на пропуски
hs_test.iloc[0, 0] = np.nan
hs_test.iloc[1, 0] = None
# выводим первые четыре наблюдения
hs_test.head(4)

HouseStyle
0        NaN
1       None
2     2Story
3     2Story

In [22]:
# копируем переменную HouseStyle
# в обучающем наборе
hs_train = hs_train.copy()
# заменяем первое значение на пропуск
hs_train.iloc[0, 0] = np.nan
# создаем экземпляр класса OneHotEncoder
ohe = OneHotEncoder(sparse=False, handle_unknown='ignore')
# выполняем дамми-кодирование переменной 
# HouseStyle в обучающем наборе
ohe.fit_transform(hs_train)

ValueError: Input contains NaN

In [23]:
# копируем переменную HouseStyle
# в обучающем наборе
hs_train = train[['HouseStyle']].copy()
# заменяем первое значение на пропуск
hs_train.iloc[0, 0] = np.nan
# импортируем класс SimpleImputer
from sklearn.impute import SimpleImputer
# создаем экземпляр класса SimpleImputer
si = SimpleImputer(strategy='constant', fill_value='MISSING')
# выполняем импутацию
hs_train_imputed = si.fit_transform(hs_train)
hs_train_imputed

array([['MISSING'],
       ['1Story'],
       ['2Story'],
       ...,
       ['2Story'],
       ['1Story'],
       ['1Story']], dtype=object)

In [24]:
# выполняем дамми-кодирование переменной HouseStyle 
# в импутированном обучающем наборе
hs_train_transformed = ohe.fit_transform(hs_train_imputed)
hs_train_transformed

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [25]:
# копируем переменную HouseStyle
# в тестовом наборе
hs_test = test[['HouseStyle']].copy()
# заменяем первые два значения на новое 
# строковое значение и пропуск
hs_test.iloc[0, 0] = 'unique value to test set'
hs_test.iloc[1, 0] = np.nan
# выполняем импутацию
hs_test_imputed = si.transform(hs_test)
# выполняем дамми-кодирование
hs_test_transformed = ohe.transform(hs_test_imputed)
# убеждаемся, что каждое уникальное значение
# получило свой столбец (8 уникальных значений плюс
# 1 новое unique value to test set даст 9 столбцов)
hs_test_transformed.shape

(1459, 9)

In [26]:
# импортируем класс Pipeline
from sklearn.pipeline import Pipeline

In [27]:
# задаем этап импутации
si_step = ('si', SimpleImputer(strategy='constant',
                               fill_value='MISSING'))
# задаем этап дамми-кодирования
ohe_step = ('ohe', OneHotEncoder(sparse=False,
                                 handle_unknown='ignore'))
# создаем список этапов
steps = [si_step, ohe_step]
# создаем конвейер, передав список этапов
pipe = Pipeline(steps)
# копируем переменную HouseStyle
# в обучающем наборе
hs_train = train[['HouseStyle']].copy()
# заменяем первое значение на пропуск
hs_train.iloc[0, 0] = np.nan
# выполняем импутацию и дамми-кодирование
# переменной HouseStyle в обучающем наборе
# с помощью каждого этапа конвейера
hs_transformed = pipe.fit_transform(hs_train)
# убеждаемся, что каждое уникальное значение
# получило свой столбец (8 уникальных значений
# плюс 1 новое MISSING даст 9 столбцов)
hs_transformed.shape

(1460, 9)

In [28]:
# копируем переменную HouseStyle
# в тестовом наборе
hs_test = test[['HouseStyle']].copy()
# выполняем импутацию и дамми-кодирование
# переменной HouseStyle в тестовом наборе
# с помощью каждого этапа конвейера
hs_test_transformed = pipe.transform(hs_test)
# убеждаемся, что каждое уникальное значение
# получило свой столбец (8 уникальных значений
# плюс 1 новое MISSING даст 9 столбцов)
hs_test_transformed.shape

(1459, 9)

In [29]:
# создаем список столбцов RoofMatl и HouseStyle
# со строковыми значениями
string_cols = ['RoofMatl', 'HouseStyle']
# создаем датафрейм из двух столбцов
# RoofMatl и HouseStyle
string_train = train[string_cols]
# выводим первые три наблюдения
string_train.head(3)

RoofMatl HouseStyle
0  CompShg     2Story
1  CompShg     1Story
2  CompShg     2Story

In [30]:
# обращаемся к этапу ohe
ohe = pipe.named_steps['ohe']
# извлекаем названия признаков
ohe.get_feature_names()

array(['x0_1.5Fin', 'x0_1.5Unf', 'x0_1Story', 'x0_2.5Fin', 'x0_2.5Unf',
       'x0_2Story', 'x0_MISSING', 'x0_SFoyer', 'x0_SLvl'], dtype=object)

In [31]:
# импортируем класс ColumnTransformer
from sklearn.compose import ColumnTransformer
# задаем этап импутации
cat_si_step = ('si', SimpleImputer(strategy='constant',
                                   fill_value='MISSING'))
# задаем этап дамми-кодирования
cat_ohe_step = ('ohe', OneHotEncoder(sparse=False,
                                     handle_unknown='ignore'))
# создаем список этапов
cat_steps = [cat_si_step, cat_ohe_step]
# создаем конвейер, передав список этапов
cat_pipe = Pipeline(cat_steps)
# создаем список столбцов RoofMatl и HouseStyle
# со строковыми значениями
cat_cols = ['RoofMatl', 'HouseStyle']
# создаем список с трехэлементным кортежем
cat_transformers = [('cat', cat_pipe, cat_cols)]
# передаем список в ColumnTransformer
ct = ColumnTransformer(transformers=cat_transformers)

In [32]:
# передаем обучающий набор в ColumnTransformer
X_cat_transformed = ct.fit_transform(train)
# убеждаемся, что преобразования выполнены
X_cat_transformed.shape

(1460, 16)

In [33]:
# выполняем преобразование тестового набора
X_cat_transformed_test = ct.transform(test)
# убеждаемся, что преобразования выполнены
X_cat_transformed_test.shape

(1459, 16)

In [34]:
# выбираем трансформер
pl = ct.named_transformers_['cat']

In [35]:
# извлекаем объект OneHotEncoder
ohe = pl.named_steps['ohe']
# извлекаем имена признаков
ohe.get_feature_names()

array(['x0_ClyTile', 'x0_CompShg', 'x0_Membran', 'x0_Metal', 'x0_Roll',
       'x0_Tar&Grv', 'x0_WdShake', 'x0_WdShngl', 'x1_1.5Fin', 'x1_1.5Unf',
       'x1_1Story', 'x1_2.5Fin', 'x1_2.5Unf', 'x1_2Story', 'x1_SFoyer',
       'x1_SLvl'], dtype=object)

In [36]:
# смотрим типы первых 5 признаков
train.dtypes.head()

Id               int64
MSSubClass       int64
MSZoning        object
LotFrontage    float64
LotArea          int64
dtype: object

In [37]:
# выводим тип каждой переменной в виде одной буквы
kinds = np.array([dt.kind for dt in train.dtypes])
kinds[:5]

array(['i', 'i', 'O', 'f', 'i'], dtype='<U1')

In [38]:
# создаем массив из всех признаков
all_columns = train.columns.values
# создаем массив из количественных признаков
is_num = kinds != 'O'
# отбираем только количественные признаки
num_cols = all_columns[is_num]
# выводим первые 5 количественных признаков
num_cols[:5]

array(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual'],
      dtype=object)

In [39]:
# отбираем только категориальные признаки
cat_cols = all_columns[~is_num]
# выводим первые 5 категориальных признаков
cat_cols[:5]

array(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour'],
      dtype=object)

In [40]:
# импортируем класс StandardScaler
from sklearn.preprocessing import StandardScaler
# задаем этап импутации
num_si_step = ('si', SimpleImputer(strategy='median'))
# задаем этап стандартизации
num_ss_step = ('ss', StandardScaler())
# создаем список этапов
num_steps = [num_si_step, num_ss_step]
# создаем конвейер, передав список этапов
num_pipe = Pipeline(num_steps)
# создаем список с трехэлементным кортежем
num_transformers = [('num', num_pipe, num_cols)]
# создаем трансформер, передав список
ct = ColumnTransformer(transformers=num_transformers)
# выполняем преобразования обучающего
# набора с помощью трансформера
X_num_transformed = ct.fit_transform(train)
# убеждаемся, что преобразования выполнены
X_num_transformed.shape

(1460, 37)

In [41]:
# создаем список трехэлементных кортежей, в котором
# первый элемент кортежа - название конвейера с
# преобразованиями для определенного типа признаков
transformers = [('cat', cat_pipe, cat_cols),
                ('num', num_pipe, num_cols)]
# передаем список в ColumnTransformer
ct = ColumnTransformer(transformers=transformers)
# выполняем преобразования для категориальных
# и количественных признаков
X = ct.fit_transform(train)
# убеждаемся, что преобразования выполнены
X.shape

(1460, 305)

In [42]:
# импортируем класс Ridge
from sklearn.linear_model import Ridge
# добавляем в конвейер новый этап - модель машинного обучения
# (модель гребневой регрессии)
ml_pipe = Pipeline([('transform', ct), ('ridge', Ridge())])
# выполняем преобразования и обучаем модель гребневой регрессии
ml_pipe.fit(train, y)

Pipeline(memory=None,
     steps=[('transform', ColumnTransformer(n_jobs=None, remainder='drop', sparse_threshold=0.3,
         transformer_weights=None,
         transformers=[('cat', Pipeline(memory=None,
     steps=[('si', SimpleImputer(copy=True, fill_value='MISSING', missing_values=nan,
       strategy='constant', verbos...it_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001))])

In [43]:
# оцениваем качество модели
ml_pipe.score(train, y)

0.9220545988101002

In [44]:
# импортируем класс KFold, функцию cross_val_score()
from sklearn.model_selection import KFold, cross_val_score
# создаем экземпляр класса KFold
kf = KFold(n_splits=5, shuffle=True, random_state=123)
# выполняем перекрестную проверку, конвейер размещен
# внутри цикла перекрестной проверки
cross_val_score(ml_pipe, train, y, cv=kf).mean()

0.813392001956967

In [45]:
# импортируем класс GridSearchCV
from sklearn.model_selection import GridSearchCV
# задаем сетку гиперпараметров
param_grid = {
    'transform__num__si__strategy': ['mean', 'median'],
    'ridge__alpha': [.001, 0.1, 1.0, 5, 10, 50, 100, 1000]
}
# передаем конвейер в объект GridSearchCV
gs = GridSearchCV(ml_pipe, param_grid, cv=kf, return_train_score=True)
# выполняем решетчатый поиск
gs.fit(train, y)
# смотрим наилучшие значения гиперпараметров
gs.best_params_

{'ridge__alpha': 10, 'transform__num__si__strategy': 'median'}

In [46]:
# смотрим наилучшее значение R-квадрат
gs.best_score_

0.8190367464419682

In [47]:
# представляем результаты решетчатого поиска
# в виде датафрейма pandas
pd.DataFrame(gs.cv_results_)

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.025202      0.003471         0.007229        0.001507   
1        0.026631      0.001660         0.006821        0.001156   
2        0.021862      0.001261         0.007994        0.001876   
3        0.024888      0.001535         0.006165        0.000547   
4        0.023044      0.001917         0.006949        0.000775   
5        0.024625      0.001367         0.006439        0.000518   
6        0.024263      0.002288         0.006281        0.000792   
7        0.025529      0.001706         0.007652        0.000813   
8        0.023567      0.001679         0.007452        0.001302   
9        0.024530      0.001616         0.006650        0.000801   
10       0.023101      0.002250         0.006265        0.000417   
11       0.026178      0.003850         0.007427        0.001092   
12       0.026077      0.003741         0.007534        0.001725   
13       0.023665      0.001448         0.006671        0.000741   
14       0.024206      0.004322         0.007380        0.000926   
15       0.031789      0.003413         0.007993        0.001086   

   param_ridge__alpha param_transform__num__si__strategy  \
0               0.001                               mean   
1               0.001                             median   
2                 0.1                               mean   
3                 0.1                             median   
4                   1                               mean   
5                   1                             median   
6                   5                               mean   
7                   5                             median   
8                  10                               mean   
9                  10                             median   
10                 50                               mean   
11                 50                             median   
12                100                               mean   
13                100                             median   
14               1000                               mean   
15               1000                             median   

                                               params  split0_test_score  \
0   {'ridge__alpha': 0.001, 'transform__num__si__s...           0.898019   
1   {'ridge__alpha': 0.001, 'transform__num__si__s...           0.898015   
2   {'ridge__alpha': 0.1, 'transform__num__si__str...           0.897111   
3   {'ridge__alpha': 0.1, 'transform__num__si__str...           0.897114   
4   {'ridge__alpha': 1.0, 'transform__num__si__str...           0.891715   
5   {'ridge__alpha': 1.0, 'transform__num__si__str...           0.891728   
6   {'ridge__alpha': 5, 'transform__num__si__strat...           0.889795   
7   {'ridge__alpha': 5, 'transform__num__si__strat...           0.889804   
8   {'ridge__alpha': 10, 'transform__num__si__stra...           0.890470   
9   {'ridge__alpha': 10, 'transform__num__si__stra...           0.890488   
10  {'ridge__alpha': 50, 'transform__num__si__stra...           0.888784   
11  {'ridge__alpha': 50, 'transform__num__si__stra...           0.888869   
12  {'ridge__alpha': 100, 'transform__num__si__str...           0.883419   
13  {'ridge__alpha': 100, 'transform__num__si__str...           0.883538   
14  {'ridge__alpha': 1000, 'transform__num__si__st...           0.827384   
15  {'ridge__alpha': 1000, 'transform__num__si__st...           0.827546   

    split1_test_score  split2_test_score       ...         mean_test_score  \
0            0.024032           0.775950       ...                0.648872   
1            0.024086           0.775946       ...                0.648897   
2            0.779393           0.800366       ...                0.802965   
3            0.779408           0.800366       ...                0.802984   
4            0.809381           0.822107       ...                0.813364   
5            0.809413           0.822128       ...               

In [48]:
# импортируем класс BaseEstimator
from sklearn.base import BaseEstimator

# создаем класс BasicTransformer
class BasicTransformer(BaseEstimator):
    
    def __init__(self, cat_threshold=None, num_strategy='median', return_df=False):
        # храним параметры как публичные аттрибуты
        self.cat_threshold = cat_threshold
        
        if num_strategy not in ['mean', 'median']:
            raise ValueError('num_strategy must be either "mean" or "median"')
        self.num_strategy = num_strategy
        self.return_df = return_df
        
    def fit(self, X, y=None):
        # подразумевает, что X - это объект DataFrame
        self._columns = X.columns.values
        
        # разбиваем данные на категориальные и количественные признаки
        self._dtypes = X.dtypes.values
        self._kinds = np.array([dt.kind for dt in X.dtypes])
        self._column_dtypes = {}
        is_cat = self._kinds == 'O'
        self._column_dtypes['cat'] = self._columns[is_cat]
        self._column_dtypes['num'] = self._columns[~is_cat]
        self._feature_names = self._column_dtypes['num']
        
        # создаем словарь на основе категориального признака, 
        # где ключом будет уникальное значение выше порога
        self._cat_cols = {}
        for col in self._column_dtypes['cat']:
            vc = X[col].value_counts()
            if self.cat_threshold is not None:
                vc = vc[vc > self.cat_threshold]
            vals = vc.index.values
            self._cat_cols[col] = vals
            self._feature_names = np.append(self._feature_names, col + '_' + vals)
            
        # вычисляем общее количество новых категориальных признаков    
        self._total_cat_cols = sum([len(v) for col, v in self._cat_cols.items()])
        
        # вычисляем среднее или медиану
        self._num_fill = X[self._column_dtypes['num']].agg(self.num_strategy)
        return self    
        
    def transform(self, X):
        # проверяем, есть ли у нас объект DataFrame с теми же именами столбцов, 
        # что и в том объекте DataFrame, который использовался для обучения
        if set(self._columns) != set(X.columns):
            raise ValueError('Passed DataFrame has diff cols than fit DataFrame')
        elif len(self._columns) != len(X.columns):
            raise ValueError('Passed DataFrame has diff number of cols than fit DataFrame')
            
        # заполняем пропуски 
        X_num = X[self._column_dtypes['num']].fillna(self._num_fill)            
            
        # стандартизируем количественные признаки
        std = X_num.std()
        X_num = (X_num - X_num.mean()) / std
        zero_std = np.where(std == 0)[0]             
        
        # Если стандартное отклонение 0, то все значения идентичны. Задаем их равными 0.
        if len(zero_std) > 0:
            X_num.iloc[:, zero_std] = 0
        X_num = X_num.values
        
        # создаем отдельный массив для преобразованных категориальных признаков
        X_cat = np.empty((len(X), self._total_cat_cols), dtype='int')
        i = 0
        for col in self._column_dtypes['cat']:
            vals = self._cat_cols[col]
            for val in vals:
                X_cat[:, i] = X[col] == val
                i += 1
                
        # конкатенируем преобразованные количественные и категориальные признаки
        data = np.column_stack((X_num, X_cat))
        
        # возвращаем либо DataFrame, либо массив
        if self.return_df:
            return pd.DataFrame(data=data, columns=self._feature_names)
        else:
            return data
    
    def fit_transform(self, X, y=None):
        return self.fit(X).transform(X)
    
    def get_feature_names(self):
        return self._feature_names

In [49]:
# создаем экземпляр класса BasicTransformer
bt = BasicTransformer(cat_threshold=3, return_df=True)
# выполняем преобразование обучающего
# набора с помощью BasicTransformer
train_transformed = bt.fit_transform(train)
# выводим первые 3 наблюдения
train_transformed.head(3)

Id  MSSubClass  LotFrontage   LotArea  OverallQual  OverallCond  \
0 -1.730272    0.073350    -0.220799 -0.207071     0.651256    -0.517023   
1 -1.727900   -0.872264     0.460162 -0.091855    -0.071812     2.178881   
2 -1.725528    0.073350    -0.084607  0.073455     0.651256    -0.517023   

   YearBuilt  YearRemodAdd  MasVnrArea  BsmtFinSF1          ...            \
0   1.050634      0.878367    0.513928    0.575228          ...             
1   0.156680     -0.429430   -0.570555    1.171591          ...             
2   0.984415      0.829930    0.325803    0.092875          ...             

   SaleType_ConLD  SaleType_ConLw  SaleType_ConLI  SaleType_CWD  \
0             0.0             0.0             0.0           0.0   
1             0.0             0.0             0.0           0.0   
2             0.0             0.0             0.0           0.0   

   SaleCondition_Normal  SaleCondition_Partial  SaleCondition_Abnorml  \
0                   1.0                    0.0                    0.0   
1                   1.0                    0.0                    0.0   
2                   1.0                    0.0                    0.0   

   SaleCondition_Family  SaleCondition_Alloca  SaleCondition_AdjLand  
0                   0.0                   0.0                    0.0  
1                   0.0                   0.0                    0.0  
2                   0.0                   0.0                    0.0  

[3 rows x 246 columns]

In [50]:
# передаем наш BasicTransformer в конвейер
basic_pipe = Pipeline([('bt', bt), ('ridge', Ridge())])
# выполняем преобразования и строим модель гребневой регрессии
basic_pipe.fit(train, y)
# оцениваем качество модели
basic_pipe.score(train, y)

0.9035633239411639

In [51]:
# передаем наш конвейер в цикл перекрестной проверки
cross_val_score(basic_pipe, train, y, cv=kf).mean()

0.8157670129480052

In [52]:
# задаем сетку гиперпараметров
param_grid = {
    'bt__cat_threshold': [0, 1, 2, 3, 5],
    'ridge__alpha': [.1, 1, 10, 100]
}
# передаем наш конвейер в объект GridSearchCV
gs = GridSearchCV(basic_pipe, param_grid, cv=kf)
# выполняем решетчатый поиск
gs.fit(train, y)
# смотрим наилучшие значения гиперпараметров
gs.best_params_

{'bt__cat_threshold': 0, 'ridge__alpha': 10}

In [53]:
# смотрим наилучшее значение R-квадрат
gs.best_score_

0.8297473585998103

In [54]:
# импортируем класс KBinsDiscretizer
from sklearn.preprocessing import KBinsDiscretizer
# создаем экземпляр класса KBinsDiscretizer
kbd = KBinsDiscretizer(encode='onehot-dense')
# выполняем биннинг
year_built_transformed = kbd.fit_transform(train[['YearBuilt']])
# смотрим результаты
year_built_transformed

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [55]:
# убедимся, что бины содержать примерно
# одинаковое количество наблюдений
year_built_transformed.sum(axis=0)

array([292., 274., 307., 266., 321.])

In [56]:
# посмотрим на границы бинов
kbd.bin_edges_

array([array([1872. , 1947.8, 1965. , 1984. , 2003. , 2010. ])],
      dtype=object)

In [57]:
# выделяем переменные с годами в отдельный список
year_cols = ['YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 
             'YrSold']
# создаем булев массив
not_year = ~np.isin(num_cols, year_cols + ['Id'])
# выделяем количественные переменные, исключив
# переменные с годами и Id
num_cols2 = num_cols[not_year]
# создаем этап импутации
year_si_step = ('si', SimpleImputer(strategy='median'))
# создаем этап биннинга
year_kbd_step = ('kbd', KBinsDiscretizer(n_bins=5, 
                                         encode='onehot-dense'))
# создаем список этапов
year_steps = [year_si_step, year_kbd_step]
# создаем конвейер, передав список этапов
year_pipe = Pipeline(year_steps)
# создаем список трехэлементный кортежей, в котором
# первый элемент кортежа - название конвейера с
# преобразованиями для определенного типа признаков
transformers = [('cat', cat_pipe, cat_cols),
                ('num', num_pipe, num_cols2),
                ('year', year_pipe, year_cols)]
# создаем трансформер, передав список
ct = ColumnTransformer(transformers=transformers)
# выполняем преобразования обучающего
# набора с помощью трансформера
X = ct.fit_transform(train)
# убеждаемся, что преобразования выполнены
X.shape

(1460, 320)

In [58]:
# добавляем в конвейер новый этап - модель машинного обучения
# (модель гребневой регрессии)
ml_pipe = Pipeline([('transform', ct), ('ridge', Ridge())])
# выполняем перекрестную проверку, конвейер размещен
# внутри цикла перекрестной проверки
cross_val_score(ml_pipe, train, y, cv=kf).mean()

0.8127854010155339

In [59]:
# задаем сетку гиперпараметров
param_grid = {
    'transform__year__kbd__n_bins': [4, 6, 8, 10],
    'ridge__alpha': [.1, .5, 1, 5, 10, 100]
}
# передаем наш конвейер в объект GridSearchCV
gs = GridSearchCV(ml_pipe, param_grid, cv=kf)
# выполняем решетчатый поиск
gs.fit(train, y)
# смотрим наилучшие значения гиперпараметров
gs.best_params_

{'ridge__alpha': 10, 'transform__year__kbd__n_bins': 6}

In [60]:
# смотрим наилучшее значение R-квадрат
gs.best_score_

0.8198372622112804

In [61]:
# заново записываем CSV-файл в объект DataFrame
train = pd.read_csv('https://raw.githubusercontent.com/'
                    'DunderData/Machine-Learning-Tutorials/'
                    'master/data/housing/train.csv')

# создаем массив меток
y = train.pop('SalePrice').values

# удаляем переменную Id
train.drop('Id', axis=1, inplace=True)

In [62]:
# выделим категориальные и количественные признаки
cat_columns = train.dtypes[train.dtypes == 'object'].index
num_columns = train.dtypes[train.dtypes != 'object'].index

In [63]:
# вычислим коэффициент асимметрии для
# количественных признаков
for i in num_columns:
    print(i, train[i].skew())

MSSubClass 1.4076567471495591
LotFrontage 2.163569142324884
LotArea 12.207687851233496
OverallQual 0.2169439277628693
OverallCond 0.6930674724842182
YearBuilt -0.613461172488183
YearRemodAdd -0.5035620027004709
MasVnrArea 2.669084210182863
BsmtFinSF1 1.685503071910789
BsmtFinSF2 4.255261108933303
BsmtUnfSF 0.9202684528039037
TotalBsmtSF 1.5242545490627664
1stFlrSF 1.3767566220336365
2ndFlrSF 0.8130298163023265
LowQualFinSF 9.011341288465387
GrLivArea 1.3665603560164552
BsmtFullBath 0.596066609663168
BsmtHalfBath 4.103402697955168
FullBath 0.036561558402727165
HalfBath 0.675897448233722
BedroomAbvGr 0.21179009627507137
KitchenAbvGr 4.488396777072859
TotRmsAbvGrd 0.6763408364355531
Fireplaces 0.6495651830548841
GarageYrBlt -0.6494146238714679
GarageCars -0.3425489297486655
GarageArea 0.17998090674623907
WoodDeckSF 1.5413757571931312
OpenPorchSF 2.3643417403694404
EnclosedPorch 3.08987190371177
3SsnPorch 10.304342032693112
ScreenPorch 4.122213743143115
PoolArea 14.828373640750588
MiscVal 

In [64]:
# импортируем классы FunctionTransformer, RobustScaler
from sklearn.preprocessing import FunctionTransformer, RobustScaler

In [65]:
# выделяем список признаков с небольшой отрицательной асимметрией
neg_skew_num_columns = ['YearBuilt', 'YearRemodAdd', 'GarageYrBlt', 'GarageCars']
# выделяем список признаков с высокой положительной асимметрией
high_pos_skew_num_columns = ['MiscVal', 'PoolArea', '3SsnPorch', 'LotArea', 'LowQualFinSF']
# создадим булев массив
not_neg_high_pos_skew_num_columns = ~np.isin(
    num_columns, high_pos_skew_num_columns + neg_skew_num_columns)
# из списка количественных признаков удалим количественные признаки 
# с небольшой отрицательной и высокой положительной асимметрией
num_columns = num_columns[not_neg_high_pos_skew_num_columns]

In [66]:
# создаем конвейер преобразований для количественных признаков 
# с небольшой отрицательной асимметрией
num_negskew_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('square', FunctionTransformer(np.square, validate=False)),
    ('scaler', StandardScaler())
])

# создаем конвейер преобразований для количественных признаков 
# с небольшой и средней положительной асимметрией
num_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('log', FunctionTransformer(np.log1p, validate=False)),
    ('scaler', RobustScaler())
])

# создаем конвейер преобразований для количественных
# признаков с высокой асимметрией
num_highposskew_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('sqrt', FunctionTransformer(np.sqrt, validate=False)),
    ('kbd', KBinsDiscretizer(n_bins=5, encode='onehot-dense'))
])

# создаем конвейер преобразований для категориальных
# признаков
cat_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='constant', fill_value='MISSING')),
    ('ohe', OneHotEncoder(sparse=False, handle_unknown='ignore'))
])

transformers = [('num_negskew', num_negskew_pipe, neg_skew_num_columns),
                ('num', num_pipe, num_columns),
                ('num_highposskew', num_highposskew_pipe, high_pos_skew_num_columns),
                ('cat', cat_pipe, cat_columns)]

transformer = ColumnTransformer(transformers=transformers)

# добавляем в конвейер новый этап - модель машинного обучения
# (модель гребневой регрессии)
ml_pipe = Pipeline([('transform', transformer), ('ridge', Ridge())])
# выполняем перекрестную проверку, конвейер размещен
# внутри цикла перекрестной проверки
cross_val_score(ml_pipe, train, y, cv=kf).mean()

0.8307940999181337

In [67]:
# задаем сетку гиперпараметров
param_grid = {
    'ridge__alpha': [.1, .5, 1, 5, 10, 100],
    'transform__num_highposskew__kbd__n_bins': [3, 4, 5, 6, 7]
}
# передаем наш конвейер в объект GridSearchCV
gs = GridSearchCV(ml_pipe, param_grid, cv=kf)
# выполняем решетчатый поиск
gs.fit(train, y)
# смотрим наилучшие значения гиперпараметров
gs.best_params_

{'ridge__alpha': 10, 'transform__num_highposskew__kbd__n_bins': 7}

In [68]:
# смотрим наилучшее значение R-квадрат
gs.best_score_

0.8474547753257715

#### Больше материалов о машинном обучении и информацию о курсах по машинному обучению можно найти в нашей группе в Facebook https://www.facebook.com/groups/gewissta